### ISSUE TITLE
Are you applying for WWDC 2017?

### ISSUE THREAD

**Issue by Aviral190694** [neilsardesai/WWDC-Crowd-Simulator-2017#1]
Hey, Are you applying for WWDC 2017? I seriously loved your project. This is a brilliant idea. If you are not applying I would like to add few features and apply with this.

**Comment by neilsardesai** [comment]
Hi Aviral,
Sorry, I am applying for WWDC and using this project 😛

**Comment by Aviral190694** [comment]
Cool. Best of luck man! Great work! 
If you have some other ideas do let me know :)

**Comment by neilsardesai** [comment]
Good luck to you too!
