### ISSUE TITLE
Someone may have plagiarized your submission

### ISSUE THREAD

**Issue by ezhes** [neilsardesai/WWDC-Crowd-Simulator-2017#2]
https://www.youtube.com/watch?v=4sCd9M4uv1M

Looks like someone forked and claimed your project as their own for the scholarship.

**Comment by neilsardesai** [comment]
Oh wow. I see he took the video down, but I got a chance to see it. Pretty lame he did that :/

**Comment by ezhes** [comment]
I saved it because I knew he was going to do that. I sent Apple an email, looks like I'm going to have to send the video I saved as well.

**Comment by neilsardesai** [comment]
Dude, that's awesome. Thanks! Really appreciate your help here.

**Comment by ezhes** [comment]
Here's the video file if you need it for later reference for proof or whatever if Apple contacts you 

https://drive.google.com/file/d/0BxMdyOjswzPBMHNERWMwNDNPd1k/view?usp=sharing

**Comment by neilsardesai** [comment]
I sent Apple an email as well. Not sure what else to do about it but hopefully they’ll take care of it. By the way, I got a chance to check out your submission. It's pretty slick. Good luck to you, man!
